FROM python:13
WORKDIR /scripts/webapp

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend.py ./
EXPOSE 8501

RUN useradd app
USER app

CMD  ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.enableCORS=false"]