name: Fetch, Convert, and Upload Seismic Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensures that your repo is available for the workflow

    # Debug step to check the directory and files
      - name: Debug - List files in the repository
        run: |
          echo "Current working directory:"
          pwd
          echo "List of files:"
          ls -al

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pymongo obspy

      - name: Retrieve Seismic Data (MiniSEED)
        run: python retrieve_seismic_data.py  # Fetches fresh data

      - name: Convert MiniSEED to JSON
        run: python convert_to_json.py  # Converts to JSON

      - name: Upload JSON to MongoDB
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python upload_to_mongo.py  # Uploads JSON
